test(e2e): add assertions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,4 +26,8 @@ jobs:
           coverage run --source=src -m unittest -v
           coverage report -m --fail-under=100
       - name: Run e2e tests
-        run: python main.py
+        run: |
+          python main.py > output.log 2> error.log
+          [ -f output.log ] || (echo "File 'output.log' does not exist" && exit 1)
+          [ -f error.log ] || (echo "File 'error.log' does not exist" && exit 2)
+          [ ! -s error.log ] || (echo "File 'error.log' is not empty" && exit 3)
